apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tracetest.fullname" . }}-collector-config
data:
  otel-collector-config.yaml: |-
    {{- toYaml .Values.otelCollector.config | nindent 4 }}
